language: python
python:
  - "3.5"
  - "2.7"

sudo: required

services:
  - redis
  - docker

# Install dependencies
install: "pip install -r requirements.txt"
script: ./run_tests.sh

build:
  - docker build -t mdrudi/diffme:latest .

after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
  - docker push mdrudi/diffme
